##### Copyright 2019 The TensorFlow Authors.

In [27]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Text generation with an RNN

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/text/tutorials/text_generation"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/text_generation.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/text/blob/master/docs/tutorials/text_generation.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/text/docs/tutorials/text_generation.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial demonstrates how to generate text using a character-based RNN. You will work with a dataset of Shakespeare's writing from Andrej Karpathy's [The Unreasonable Effectiveness of Recurrent Neural Networks](http://karpathy.github.io/2015/05/21/rnn-effectiveness/). Given a sequence of characters from this data ("Shakespear"), train a model to predict the next character in the sequence ("e"). Longer sequences of text can be generated by calling the model repeatedly.

Note: Enable GPU acceleration to execute this notebook faster. In Colab: *Runtime > Change runtime type > Hardware accelerator > GPU*.

This tutorial includes runnable code implemented using [tf.keras](https://www.tensorflow.org/guide/keras/sequential_model) and [eager execution](https://www.tensorflow.org/guide/eager). The following is the sample output when the model in this tutorial trained for 30 epochs, and started with the prompt "Q":

<pre>
QUEENE:
I had thought thou hadst a Roman; for the oracle,
Thus by All bids the man against the word,
Which are so weak of care, by old care done;
Your children were in your holy love,
And the precipitation through the bleeding throne.

BISHOP OF ELY:
Marry, and will, my lord, to weep in such a one were prettiest;
Yet now I was adopted heir
Of the world's lamentable day,
To watch the next way with his father with his face?

ESCALUS:
The cause why then we are all resolved more sons.

VOLUMNIA:
O, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, it is no sin it should be dead,
And love and pale as any will to that word.

QUEEN ELIZABETH:
But how long have I heard the soul for this world,
And show his hands of life be proved to stand.

PETRUCHIO:
I say he look'd on, if I must be content
To stay him from the fatal of our country's bliss.
His lordship pluck'd from this sentence then for prey,
And then let us twain, being the moon,
were she such a case as fills m
</pre>

While some of the sentences are grammatical, most do not make sense. The model has not learned the meaning of words, but consider:

* The model is character-based. When training started, the model did not know how to spell an English word, or that words were even a unit of text.

* The structure of the output resembles a play—blocks of text generally begin with a speaker name, in all capital letters similar to the dataset.

* As demonstrated below, the model is trained on small batches of text (100 characters each), and is still able to generate a longer sequence of text with coherent structure.

## Setup

### Import TensorFlow and other libraries

In [28]:
import tensorflow as tf
import tensorflow_datasets as tfds

import numpy as np
import os
import time

c:\Users\chamo\Miniconda\envs\girls_and_boys_in_tech\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Download the Shakespeare dataset

Change the following line to run this code on your own data.

In [29]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')
#path_to_file = '..\datasets_analysis\kaggle_mental_health_conversation_txt.txt'

### Read the data

First, look in the text:

In [30]:
# Read, then decode for py2 compat.
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')
# length of text is the number of characters in it
print(f'Length of text: {len(text)} characters')

Length of text: 1115394 characters


In [31]:
# Take a look at the first 250 characters in text
print(text[:250])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.



In [32]:
# The unique characters in the file
vocab = sorted(set(text))
print(f'{len(vocab)} unique characters')

65 unique characters


## Process the text

### Vectorize the text

Before training, you need to convert the strings to a numerical representation. 

The `tf.keras.layers.StringLookup` layer can convert each character into a numeric ID. It just needs the text to be split into tokens first.

In [33]:
example_texts = ['abcdefg', 'xyz']

chars = tf.strings.unicode_split(example_texts, input_encoding='UTF-8')
chars

<tf.RaggedTensor [[b'a', b'b', b'c', b'd', b'e', b'f', b'g'], [b'x', b'y', b'z']]>

Now create the `tf.keras.layers.StringLookup` layer:

In [34]:
ids_from_chars = tf.keras.layers.StringLookup(
    vocabulary=list(vocab), mask_token=None)

It converts from tokens to character IDs:

In [35]:
ids = ids_from_chars(chars)
ids

<tf.RaggedTensor [[40, 41, 42, 43, 44, 45, 46], [63, 64, 65]]>

Since the goal of this tutorial is to generate text, it will also be important to invert this representation and recover human-readable strings from it. For this you can use `tf.keras.layers.StringLookup(..., invert=True)`.  

Note: Here instead of passing the original vocabulary generated with `sorted(set(text))` use the `get_vocabulary()` method of the `tf.keras.layers.StringLookup` layer so that the `[UNK]` tokens is set the same way.

In [36]:
chars_from_ids = tf.keras.layers.StringLookup(
    vocabulary=ids_from_chars.get_vocabulary(), invert=True, mask_token=None)

This layer recovers the characters from the vectors of IDs, and returns them as a `tf.RaggedTensor` of characters:

In [37]:
chars = chars_from_ids(ids)
chars

<tf.RaggedTensor [[b'a', b'b', b'c', b'd', b'e', b'f', b'g'], [b'x', b'y', b'z']]>

You can `tf.strings.reduce_join` to join the characters back into strings. 

In [38]:
tf.strings.reduce_join(chars, axis=-1).numpy()

array([b'abcdefg', b'xyz'], dtype=object)

In [39]:
def text_from_ids(ids):
  return tf.strings.reduce_join(chars_from_ids(ids), axis=-1)

### The prediction task

Given a character, or a sequence of characters, what is the most probable next character? This is the task you're training the model to perform. The input to the model will be a sequence of characters, and you train the model to predict the output—the following character at each time step.

Since RNNs maintain an internal state that depends on the previously seen elements, given all the characters computed until this moment, what is the next character?


### Create training examples and targets

Next divide the text into example sequences. Each input sequence will contain `seq_length` characters from the text.

For each input sequence, the corresponding targets contain the same length of text, except shifted one character to the right.

So break the text into chunks of `seq_length+1`. For example, say `seq_length` is 4 and our text is "Hello". The input sequence would be "Hell", and the target sequence "ello".

To do this first use the `tf.data.Dataset.from_tensor_slices` function to convert the text vector into a stream of character indices.

In [40]:
all_ids = ids_from_chars(tf.strings.unicode_split(text, 'UTF-8'))
all_ids

<tf.Tensor: shape=(1115394,), dtype=int64, numpy=array([19, 48, 57, ..., 46,  9,  1], dtype=int64)>

In [41]:
ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)

In [42]:
for ids in ids_dataset.take(10):
    print(chars_from_ids(ids).numpy().decode('utf-8'))

F
i
r
s
t
 
C
i
t
i


In [43]:
seq_length = 100


The `batch` method lets you easily convert these individual characters to sequences of the desired size.

In [44]:
sequences = ids_dataset.batch(seq_length+1, drop_remainder=True)

for seq in sequences.take(1):
  print(chars_from_ids(seq))

tf.Tensor(
[b'F' b'i' b'r' b's' b't' b' ' b'C' b'i' b't' b'i' b'z' b'e' b'n' b':'
 b'\n' b'B' b'e' b'f' b'o' b'r' b'e' b' ' b'w' b'e' b' ' b'p' b'r' b'o'
 b'c' b'e' b'e' b'd' b' ' b'a' b'n' b'y' b' ' b'f' b'u' b'r' b't' b'h'
 b'e' b'r' b',' b' ' b'h' b'e' b'a' b'r' b' ' b'm' b'e' b' ' b's' b'p'
 b'e' b'a' b'k' b'.' b'\n' b'\n' b'A' b'l' b'l' b':' b'\n' b'S' b'p' b'e'
 b'a' b'k' b',' b' ' b's' b'p' b'e' b'a' b'k' b'.' b'\n' b'\n' b'F' b'i'
 b'r' b's' b't' b' ' b'C' b'i' b't' b'i' b'z' b'e' b'n' b':' b'\n' b'Y'
 b'o' b'u' b' '], shape=(101,), dtype=string)


It's easier to see what this is doing if you join the tokens back into strings:

In [45]:
for seq in sequences.take(5):
  print(text_from_ids(seq).numpy())

b'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
b'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'
b"now Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us ki"
b"ll him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be d"
b'one: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citi'


For training you'll need a dataset of `(input, label)` pairs. Where `input` and 
`label` are sequences. At each time step the input is the current character and the label is the next character. 

Here's a function that takes a sequence as input, duplicates, and shifts it to align the input and label for each timestep:

In [46]:
def split_input_target(sequence):
    input_text = sequence[:-1]
    target_text = sequence[1:]
    return input_text, target_text

In [47]:
split_input_target(list("Tensorflow"))

(['T', 'e', 'n', 's', 'o', 'r', 'f', 'l', 'o'],
 ['e', 'n', 's', 'o', 'r', 'f', 'l', 'o', 'w'])

In [48]:
dataset = sequences.map(split_input_target)

In [49]:
for input_example, target_example in dataset.take(1):
    print("Input :", text_from_ids(input_example).numpy())
    print("Target:", text_from_ids(target_example).numpy())

Input : b'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'
Target: b'irst Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '


### Create training batches

You used `tf.data` to split the text into manageable sequences. But before feeding this data into the model, you need to shuffle the data and pack it into batches.

In [50]:
# Batch size
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

In [51]:
test = tfds.as_numpy(dataset)
test = iter(test)
train_batch = next(test)

In [52]:
train_batch

(array([[53, 48, 46, ..., 54, 53, 54],
        [14, 60, 52, ..., 26, 40, 53],
        [44,  2, 59, ..., 51,  2, 45],
        ...,
        [ 2, 40, 53, ...,  2, 59, 47],
        [ 1,  1, 30, ..., 59, 47, 44],
        [54, 57, 40, ..., 58,  2, 46]], dtype=int64),
 array([[48, 46, 47, ..., 53, 54, 60],
        [60, 52, 44, ..., 40, 53, 64],
        [ 2, 59, 47, ...,  2, 45, 44],
        ...,
        [40, 53, 43, ..., 59, 47, 44],
        [ 1, 30, 34, ..., 47, 44,  2],
        [57, 40, 53, ...,  2, 46, 57]], dtype=int64))

## Build The Model

This section defines the model as a `keras.Model` subclass (For details see [Making new Layers and Models via subclassing](https://www.tensorflow.org/guide/keras/custom_layers_and_models)). 

This model has three layers:

* `tf.keras.layers.Embedding`: The input layer. A trainable lookup table that will map each character-ID to a vector with `embedding_dim` dimensions;
* `tf.keras.layers.GRU`: A type of RNN with size `units=rnn_units` (You can also use an LSTM layer here.)
* `tf.keras.layers.Dense`: The output layer, with `vocab_size` outputs. It outputs one logit for each character in the vocabulary. These are the log-likelihood of each character according to the model.

In [53]:
# Length of the vocabulary in StringLookup Layer
vocab_size = len(ids_from_chars.get_vocabulary())

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [54]:
class MyModel(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim, rnn_units):
    super().__init__(self)
    self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
    self.gru = tf.keras.layers.GRU(rnn_units,
                                   return_sequences=True,
                                   return_state=True)
    self.dense = tf.keras.layers.Dense(vocab_size)

  def call(self, inputs, states=None, return_state=False, training=False):
    x = inputs
    x = self.embedding(x, training=training)
    if states is None:
      states = self.gru.get_initial_state(x)
    x, states = self.gru(x, initial_state=states, training=training)
    x = self.dense(x, training=training)

    if return_state:
      return x, states
    else:
      return x

In [55]:
model = MyModel(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)

For each character the model looks up the embedding, runs the GRU one timestep with the embedding as input, and applies the dense layer to generate logits predicting the log-likelihood of the next character:

![A drawing of the data passing through the model](images/text_generation_training.png)

Note: For training you could use a `keras.Sequential` model here. To  generate text later you'll need to manage the RNN's internal state. It's simpler to include the state input and output options upfront, than it is to rearrange the model architecture later. For more details see the [Keras RNN guide](https://www.tensorflow.org/guide/keras/rnn#rnn_state_reuse).

## Try the model

Now run the model to see that it behaves as expected.

First check the shape of the output:

In [56]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 66) # (batch_size, sequence_length, vocab_size)


In [57]:
for input_example_batch, target_example_batch in dataset.take(1):
    print(input_example_batch)

tf.Tensor(
[[48 51 59 ...  1  1 29]
 [43  2 64 ... 41 51 44]
 [40 59  2 ...  2 59 47]
 ...
 [61 44  1 ... 60 57  2]
 [44 57 44 ... 59 60 43]
 [53 48 58 ... 47 40 59]], shape=(64, 100), dtype=int64)


In the above example the sequence length of the input is `100` but the model can be run on inputs of any length:

In [58]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       multiple                  16896     
                                                                 
 gru (GRU)                   multiple                  3938304   
                                                                 
 dense (Dense)               multiple                  67650     
                                                                 
Total params: 4022850 (15.35 MB)
Trainable params: 4022850 (15.35 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


To get actual predictions from the model you need to sample from the output distribution, to get actual character indices. This distribution is defined by the logits over the character vocabulary.

Note: It is important to _sample_ from this distribution as taking the _argmax_ of the distribution can easily get the model stuck in a loop.

Try it for the first example in the batch:

In [59]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

This gives us, at each timestep, a prediction of the next character index:

In [60]:
sampled_indices

array([20, 43, 64, 60, 59, 60, 35, 44, 40,  2,  4, 53, 27, 60, 38, 31, 19,
       54, 51, 22, 23, 12, 26,  4,  1, 39, 38, 48, 51, 44, 42, 24,  3, 44,
       12,  5, 47, 65, 29,  1, 43,  3, 49,  1, 49, 50,  0, 49, 49, 30, 14,
       48, 58, 14, 41, 59, 15, 63, 53, 38, 47, 23, 53, 31, 21, 27, 33, 21,
        8, 56, 30, 20, 45, 52, 22,  3, 32, 24, 27, 15, 65, 51,  9, 59, 43,
        4, 53,  4,  2, 52, 54, 25, 60, 38, 31, 13,  7, 23, 32, 20],
      dtype=int64)

Decode these to see the text predicted by this untrained model:

In [61]:
print("Input:\n", text_from_ids(input_example_batch[0]).numpy())
print()
print("Next Char Predictions:\n", text_from_ids(sampled_indices).numpy())

Input:
 b'ilt thou provoke me? then have at thee, boy!\n\nPAGE:\nO Lord, they fight! I will go call the watch.\n\nP'

Next Char Predictions:
 b'GdyutuVea $nNuYRFolIJ;M$\nZYilecK!e;&hzP\nd!j\njk[UNK]jjQAisAbtBxnYhJnRHNTH-qQGfmI!SKNBzl.td$n$ moLuYR?,JSG'


## Train the model

At this point the problem can be treated as a standard classification problem. Given the previous RNN state, and the input this time step, predict the class of the next character.

### Attach an optimizer, and a loss function

The standard `tf.keras.losses.sparse_categorical_crossentropy` loss function works in this case because it is applied across the last dimension of the predictions.

Because your model returns logits, you need to set the `from_logits` flag.


In [62]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)

In [63]:
example_batch_mean_loss = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("Mean loss:        ", example_batch_mean_loss)

Prediction shape:  (64, 100, 66)  # (batch_size, sequence_length, vocab_size)
Mean loss:         tf.Tensor(4.19066, shape=(), dtype=float32)


A newly initialized model shouldn't be too sure of itself, the output logits should all have similar magnitudes. To confirm this you can check that the exponential of the mean loss is approximately equal to the vocabulary size. A much higher loss means the model is sure of its wrong answers, and is badly initialized:

In [64]:
tf.exp(example_batch_mean_loss).numpy()

66.06638

Configure the training procedure using the `tf.keras.Model.compile` method. Use `tf.keras.optimizers.Adam` with default arguments and the loss function.

In [65]:
model.compile(optimizer='adam', loss=loss)

### Configure checkpoints

Use a `tf.keras.callbacks.ModelCheckpoint` to ensure that checkpoints are saved during training:

In [66]:
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

### Execute the training

To keep training time reasonable, use 10 epochs to train the model. In Colab, set the runtime to GPU for faster training.

In [67]:
EPOCHS = 20

In [68]:
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/20


KeyboardInterrupt: 

In [ ]:
import tensorflow_datasets as tfds
test = tfds.as_numpy(dataset)
np.shape(test)

()

## Generate text

The simplest way to generate text with this model is to run it in a loop, and keep track of the model's internal state as you execute it.

![To generate text the model's output is fed back to the input](images/text_generation_sampling.png)

Each time you call the model you pass in some text and an internal state. The model returns a prediction for the next character and its new state. Pass the prediction and state back in to continue generating text.


The following makes a single step prediction:

In [ ]:
class OneStep(tf.keras.Model):
  def __init__(self, model, chars_from_ids, ids_from_chars, temperature=1.0):
    super().__init__()
    self.temperature = temperature
    self.model = model
    self.chars_from_ids = chars_from_ids
    self.ids_from_chars = ids_from_chars

    # Create a mask to prevent "[UNK]" from being generated.
    skip_ids = self.ids_from_chars(['[UNK]'])[:, None]
    sparse_mask = tf.SparseTensor(
        # Put a -inf at each bad index.
        values=[-float('inf')]*len(skip_ids),
        indices=skip_ids,
        # Match the shape to the vocabulary
        dense_shape=[len(ids_from_chars.get_vocabulary())])
    self.prediction_mask = tf.sparse.to_dense(sparse_mask)

  @tf.function
  def generate_one_step(self, inputs, states=None):
    # Convert strings to token IDs.
    input_chars = tf.strings.unicode_split(inputs, 'UTF-8')
    input_ids = self.ids_from_chars(input_chars).to_tensor()

    # Run the model.
    # predicted_logits.shape is [batch, char, next_char_logits]
    predicted_logits, states = self.model(inputs=input_ids, states=states,
                                          return_state=True)
    # Only use the last prediction.
    predicted_logits = predicted_logits[:, -1, :]
    predicted_logits = predicted_logits/self.temperature
    # Apply the prediction mask: prevent "[UNK]" from being generated.
    predicted_logits = predicted_logits + self.prediction_mask

    # Sample the output logits to generate token IDs.
    predicted_ids = tf.random.categorical(predicted_logits, num_samples=1)
    predicted_ids = tf.squeeze(predicted_ids, axis=-1)

    # Convert from token ids to characters
    predicted_chars = self.chars_from_ids(predicted_ids)

    # Return the characters and model state.
    return predicted_chars, states

In [ ]:
one_step_model = OneStep(model, chars_from_ids, ids_from_chars)

Run it in a loop to generate some text. Looking at the generated text, you'll see the model knows when to capitalize, make paragraphs and imitates a Shakespeare-like writing vocabulary. With the small number of training epochs, it has not yet learned to form coherent sentences.

In [ ]:
start = time.time()
states = None
next_char = tf.constant(['ROMEO:'])
result = [next_char]

for n in range(1000):
  next_char, states = one_step_model.generate_one_step(next_char, states=states)
  result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result[0].numpy().decode('utf-8'), '\n\n' + '_'*80)
print('\nRun time:', end - start)

ROMEO:
The dayning use your brodous parchemn a memaver
But to my shrow against it.

CURTIS:
Do you think of't, leaving too?

QUEEN ELIZABETH:
It is, sir, let's see: to put my freedy-sorrow
In the resolution of the fell as of;
And she shall to the fish, whose parts-have
drey'd the process or owe we eptits the abtent,
That they have often been men asiel, as now
I lay stoly to none of your adversary title.
Nay, stay, what, nurse, shall I respect by him. Assisted with,
Hadst thou depart; we should have seen some name of meat:
Might from this coast was though his purpose, and they can ffor me to
And lack upon your royal king.

DUKE VINCENTIO:
It is now pale; but not a man with winds,
And breathed sunshine way: in give of less, the nurse
In thy extreme budden and his wives.
One more, most noble friend.

Third Servingman:
I have no more of it.

FRIAR LAURENCE:
O, she is found withal. Hark ye
and given me thence at we? or die among thes?
Evermother, Thomas, Duke old York and him,
So fast aspec

The easiest thing you can do to improve the results is to train it for longer (try `EPOCHS = 30`).

You can also experiment with a different start string, try adding another RNN layer to improve the model's accuracy, or adjust the temperature parameter to generate more or less random predictions.

If you want the model to generate text *faster* the easiest thing you can do is batch the text generation. In the example below the model generates 5 outputs in about the same time it took to generate 1 above. 

In [ ]:
start = time.time()
states = None
next_char = tf.constant(['ROMEO:', 'ROMEO:', 'ROMEO:', 'ROMEO:', 'ROMEO:'])
result = [next_char]

for n in range(1000):
  next_char, states = one_step_model.generate_one_step(next_char, states=states)
  result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result, '\n\n' + '_'*80)
print('\nRun time:', end - start)

tf.Tensor(
[b"ROMEO:\nFirst, heaven leave us: O, rest thy wild,\nI will my father dead?\n\nTRANIO:\nBut did you send us run; lay, fool!\nI would the world say no; what brought to? hear?\n\nKATHARINA:\nFear you the heavess to take away the time\nof a kiss of sold murder, to keep this luck\nWhose uncle branches order, I cry you\ndo, and the moting father of the like days\nThey shall seem from reason, whilst I live or else\nTo raise his writing fallent to speak.\nBut, Clifford, he is gone unto these wents were faults.\n\nLUCENTIO:\nAh, Warwick, art thou hear, the worst of in my false\nMoth thy meaning brave through the seas.\nIn what occasion not thyself?\n\nMONTAGUE:\nGood queen; Antigons, and brave amazed at the\ngreaty will out-plane. Calm those that valiant quench,\nthough us't! it is your baseness. Come, sit down;\nFor, madam: son, away! Now, by the worst.\n\nAll:\nTeems as it hath mest.\n\nDORSET:\nAnd love as you; I could heed home.\nAlas! I needs must out, as thou art a\nfraitors 

## Export the generator

This single-step model can easily be [saved and restored](https://www.tensorflow.org/guide/saved_model), allowing you to use it anywhere a `tf.saved_model` is accepted.

In [ ]:
tf.saved_model.save(one_step_model, 'one_step')
one_step_reloaded = tf.saved_model.load('one_step')

INFO:tensorflow:Assets written to: one_step/assets


INFO:tensorflow:Assets written to: one_step/assets


In [ ]:
states = None
next_char = tf.constant(['ROMEO:'])
result = [next_char]

for n in range(100):
  next_char, states = one_step_reloaded.generate_one_step(next_char, states=states)
  result.append(next_char)

print(tf.strings.join(result)[0].numpy().decode("utf-8"))

ROMEO:
While shall we toward them, gaunt and married. Urped me say I
doubt not, for this world is gentle, 


## Advanced: Customized Training

The above training procedure is simple, but does not give you much control.
It uses teacher-forcing which prevents bad predictions from being fed back to the model, so the model never learns to recover from mistakes.

So now that you've seen how to run the model manually next you'll implement the training loop. This gives a starting point if, for example, you want to implement _curriculum  learning_ to help stabilize the model's open-loop output.

The most important part of a custom training loop is the train step function.

Use `tf.GradientTape` to track the gradients. You can learn more about this approach by reading the [eager execution guide](https://www.tensorflow.org/guide/eager).

The basic procedure is:

1. Execute the model and calculate the loss under a `tf.GradientTape`.
2. Calculate the updates and apply them to the model using the optimizer.

In [ ]:
class CustomTraining(MyModel):
  @tf.function
  def train_step(self, inputs):
      inputs, labels = inputs
      with tf.GradientTape() as tape:
          predictions = self(inputs, training=True)
          loss = self.loss(labels, predictions)
      grads = tape.gradient(loss, model.trainable_variables)
      self.optimizer.apply_gradients(zip(grads, model.trainable_variables))

      return {'loss': loss}

The above implementation of the `train_step` method follows [Keras' `train_step` conventions](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit). This is optional, but it allows you to change the behavior of the train step and still use keras' `Model.compile` and `Model.fit` methods.

In [ ]:
model = CustomTraining(
    vocab_size=len(ids_from_chars.get_vocabulary()),
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)

In [ ]:
model.compile(optimizer = tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [ ]:
model.fit(dataset, epochs=1)


  1/172 [..............................] - ETA: 10:00 - loss: 4.1898


  2/172 [..............................] - ETA: 16s - loss: 4.1720  


  3/172 [..............................] - ETA: 16s - loss: 4.1475


  4/172 [..............................] - ETA: 13s - loss: 4.0987


  6/172 [>.............................] - ETA: 11s - loss: 4.3665


  7/172 [>.............................] - ETA: 12s - loss: 4.3087


  9/172 [>.............................] - ETA: 10s - loss: 4.2429


 10/172 [>.............................] - ETA: 10s - loss: 4.2212


 11/172 [>.............................] - ETA: 10s - loss: 4.2029


 12/172 [=>............................] - ETA: 10s - loss: 4.1870


 13/172 [=>............................] - ETA: 10s - loss: 4.1735


 14/172 [=>............................] - ETA: 9s - loss: 4.1605 


 15/172 [=>............................] - ETA: 10s - loss: 4.1481


 17/172 [=>............................] - ETA: 9s - loss: 4.1240 


 18/172 [==>...........................] - ETA: 9s - loss: 4.1112


 19/172 [==>...........................] - ETA: 9s - loss: 4.0975


 20/172 [==>...........................] - ETA: 9s - loss: 4.0829


 21/172 [==>...........................] - ETA: 9s - loss: 4.0667


 22/172 [==>...........................] - ETA: 9s - loss: 4.0469


 23/172 [===>..........................] - ETA: 9s - loss: 4.0231


 24/172 [===>..........................] - ETA: 9s - loss: 3.9964


 25/172 [===>..........................] - ETA: 8s - loss: 3.9713


 26/172 [===>..........................] - ETA: 8s - loss: 3.9474


 27/172 [===>..........................] - ETA: 8s - loss: 3.9216


 28/172 [===>..........................] - ETA: 8s - loss: 3.8977


 29/172 [====>.........................] - ETA: 8s - loss: 3.8746


 30/172 [====>.........................] - ETA: 8s - loss: 3.8526


 31/172 [====>.........................] - ETA: 8s - loss: 3.8309


 32/172 [====>.........................] - ETA: 8s - loss: 3.8114


 33/172 [====>.........................] - ETA: 8s - loss: 3.7920


 34/172 [====>.........................] - ETA: 8s - loss: 3.7731


 35/172 [=====>........................] - ETA: 8s - loss: 3.7551


 36/172 [=====>........................] - ETA: 8s - loss: 3.7373


 37/172 [=====>........................] - ETA: 7s - loss: 3.7191


 38/172 [=====>........................] - ETA: 7s - loss: 3.7022


 39/172 [=====>........................] - ETA: 7s - loss: 3.6853


 40/172 [=====>........................] - ETA: 7s - loss: 3.6685


 41/172 [======>.......................] - ETA: 7s - loss: 3.6521


 42/172 [======>.......................] - ETA: 7s - loss: 3.6357


 43/172 [======>.......................] - ETA: 7s - loss: 3.6202


 44/172 [======>.......................] - ETA: 7s - loss: 3.6046


 45/172 [======>.......................] - ETA: 7s - loss: 3.5898


 46/172 [=======>......................] - ETA: 7s - loss: 3.5753


 47/172 [=======>......................] - ETA: 7s - loss: 3.5611


 48/172 [=======>......................] - ETA: 7s - loss: 3.5473


 49/172 [=======>......................] - ETA: 7s - loss: 3.5329


 50/172 [=======>......................] - ETA: 7s - loss: 3.5187


 51/172 [=======>......................] - ETA: 7s - loss: 3.5050


 52/172 [========>.....................] - ETA: 6s - loss: 3.4921


 53/172 [========>.....................] - ETA: 6s - loss: 3.4791


 54/172 [========>.....................] - ETA: 6s - loss: 3.4654


 55/172 [========>.....................] - ETA: 6s - loss: 3.4518


 56/172 [========>.....................] - ETA: 6s - loss: 3.4384


 57/172 [========>.....................] - ETA: 6s - loss: 3.4260


 58/172 [=========>....................] - ETA: 6s - loss: 3.4134


 59/172 [=========>....................] - ETA: 6s - loss: 3.4007


 60/172 [=========>....................] - ETA: 6s - loss: 3.3888


 61/172 [=========>....................] - ETA: 6s - loss: 3.3762


 62/172 [=========>....................] - ETA: 6s - loss: 3.3641


 63/172 [=========>....................] - ETA: 6s - loss: 3.3531


 64/172 [==========>...................] - ETA: 6s - loss: 3.3419


 65/172 [==========>...................] - ETA: 6s - loss: 3.3304


 66/172 [==========>...................] - ETA: 6s - loss: 3.3189


 67/172 [==========>...................] - ETA: 6s - loss: 3.3080


 68/172 [==========>...................] - ETA: 6s - loss: 3.2974


 69/172 [===========>..................] - ETA: 5s - loss: 3.2871


 70/172 [===========>..................] - ETA: 5s - loss: 3.2770


 71/172 [===========>..................] - ETA: 5s - loss: 3.2669


 72/172 [===========>..................] - ETA: 5s - loss: 3.2564


 73/172 [===========>..................] - ETA: 5s - loss: 3.2466


 74/172 [===========>..................] - ETA: 5s - loss: 3.2366


 75/172 [============>.................] - ETA: 5s - loss: 3.2273


 76/172 [============>.................] - ETA: 5s - loss: 3.2180


 77/172 [============>.................] - ETA: 5s - loss: 3.2084


 78/172 [============>.................] - ETA: 5s - loss: 3.1990


 79/172 [============>.................] - ETA: 5s - loss: 3.1895


 80/172 [============>.................] - ETA: 5s - loss: 3.1803


 81/172 [=============>................] - ETA: 5s - loss: 3.1716


 82/172 [=============>................] - ETA: 5s - loss: 3.1626


 83/172 [=============>................] - ETA: 5s - loss: 3.1540


 84/172 [=============>................] - ETA: 5s - loss: 3.1459


 85/172 [=============>................] - ETA: 5s - loss: 3.1380


 87/172 [==============>...............] - ETA: 4s - loss: 3.1221


 88/172 [==============>...............] - ETA: 4s - loss: 3.1138


 89/172 [==============>...............] - ETA: 4s - loss: 3.1058


 90/172 [==============>...............] - ETA: 4s - loss: 3.0982


 91/172 [==============>...............] - ETA: 4s - loss: 3.0905


 92/172 [===============>..............] - ETA: 4s - loss: 3.0832


 93/172 [===============>..............] - ETA: 4s - loss: 3.0761


 94/172 [===============>..............] - ETA: 4s - loss: 3.0689


 95/172 [===============>..............] - ETA: 4s - loss: 3.0620


 96/172 [===============>..............] - ETA: 4s - loss: 3.0549


 97/172 [===============>..............] - ETA: 4s - loss: 3.0481


 98/172 [================>.............] - ETA: 4s - loss: 3.0415


 99/172 [================>.............] - ETA: 4s - loss: 3.0346


100/172 [================>.............] - ETA: 4s - loss: 3.0278


101/172 [================>.............] - ETA: 4s - loss: 3.0214


102/172 [================>.............] - ETA: 4s - loss: 3.0150


103/172 [================>.............] - ETA: 4s - loss: 3.0090


104/172 [=================>............] - ETA: 3s - loss: 3.0028


105/172 [=================>............] - ETA: 3s - loss: 2.9966


106/172 [=================>............] - ETA: 3s - loss: 2.9908


107/172 [=================>............] - ETA: 3s - loss: 2.9846


108/172 [=================>............] - ETA: 3s - loss: 2.9786


109/172 [==================>...........] - ETA: 3s - loss: 2.9730


110/172 [==================>...........] - ETA: 3s - loss: 2.9673


111/172 [==================>...........] - ETA: 3s - loss: 2.9618


112/172 [==================>...........] - ETA: 3s - loss: 2.9562


113/172 [==================>...........] - ETA: 3s - loss: 2.9507


114/172 [==================>...........] - ETA: 3s - loss: 2.9454


115/172 [===================>..........] - ETA: 3s - loss: 2.9401


116/172 [===================>..........] - ETA: 3s - loss: 2.9350


117/172 [===================>..........] - ETA: 3s - loss: 2.9299


118/172 [===================>..........] - ETA: 3s - loss: 2.9247


119/172 [===================>..........] - ETA: 3s - loss: 2.9198


120/172 [===================>..........] - ETA: 3s - loss: 2.9146


121/172 [====================>.........] - ETA: 2s - loss: 2.9097


122/172 [====================>.........] - ETA: 2s - loss: 2.9047


123/172 [====================>.........] - ETA: 2s - loss: 2.8999


124/172 [====================>.........] - ETA: 2s - loss: 2.8953


125/172 [====================>.........] - ETA: 2s - loss: 2.8904


126/172 [====================>.........] - ETA: 2s - loss: 2.8857


127/172 [=====================>........] - ETA: 2s - loss: 2.8811


128/172 [=====================>........] - ETA: 2s - loss: 2.8766


129/172 [=====================>........] - ETA: 2s - loss: 2.8721


130/172 [=====================>........] - ETA: 2s - loss: 2.8675


131/172 [=====================>........] - ETA: 2s - loss: 2.8630


132/172 [======================>.......] - ETA: 2s - loss: 2.8586


133/172 [======================>.......] - ETA: 2s - loss: 2.8544


134/172 [======================>.......] - ETA: 2s - loss: 2.8501


135/172 [======================>.......] - ETA: 2s - loss: 2.8455


136/172 [======================>.......] - ETA: 2s - loss: 2.8412


137/172 [======================>.......] - ETA: 2s - loss: 2.8370


138/172 [=======================>......] - ETA: 1s - loss: 2.8329


139/172 [=======================>......] - ETA: 1s - loss: 2.8287


140/172 [=======================>......] - ETA: 1s - loss: 2.8245


141/172 [=======================>......] - ETA: 1s - loss: 2.8207


142/172 [=======================>......] - ETA: 1s - loss: 2.8169


143/172 [=======================>......] - ETA: 1s - loss: 2.8129


144/172 [========================>.....] - ETA: 1s - loss: 2.8089


145/172 [========================>.....] - ETA: 1s - loss: 2.8048


146/172 [========================>.....] - ETA: 1s - loss: 2.8011


147/172 [========================>.....] - ETA: 1s - loss: 2.7972


148/172 [========================>.....] - ETA: 1s - loss: 2.7933


149/172 [========================>.....] - ETA: 1s - loss: 2.7895


150/172 [=========================>....] - ETA: 1s - loss: 2.7858


151/172 [=========================>....] - ETA: 1s - loss: 2.7825


152/172 [=========================>....] - ETA: 1s - loss: 2.7789


153/172 [=========================>....] - ETA: 1s - loss: 2.7752


154/172 [=========================>....] - ETA: 1s - loss: 2.7716


155/172 [==========================>...] - ETA: 0s - loss: 2.7679


156/172 [==========================>...] - ETA: 0s - loss: 2.7643


157/172 [==========================>...] - ETA: 0s - loss: 2.7607


158/172 [==========================>...] - ETA: 0s - loss: 2.7572


159/172 [==========================>...] - ETA: 0s - loss: 2.7538


160/172 [==========================>...] - ETA: 0s - loss: 2.7503


161/172 [===========================>..] - ETA: 0s - loss: 2.7469


162/172 [===========================>..] - ETA: 0s - loss: 2.7435


163/172 [===========================>..] - ETA: 0s - loss: 2.7401


164/172 [===========================>..] - ETA: 0s - loss: 2.7367


165/172 [===========================>..] - ETA: 0s - loss: 2.7333


166/172 [===========================>..] - ETA: 0s - loss: 2.7299


167/172 [============================>.] - ETA: 0s - loss: 2.7266


168/172 [============================>.] - ETA: 0s - loss: 2.7235


169/172 [============================>.] - ETA: 0s - loss: 2.7202


170/172 [============================>.] - ETA: 0s - loss: 2.7170


171/172 [============================>.] - ETA: 0s - loss: 2.7139


172/172 [==============================] - ETA: 0s - loss: 2.7107


172/172 [==============================] - 13s 58ms/step - loss: 2.7075


Or if you need more control, you can write your own complete custom training loop:

In [ ]:
EPOCHS = 10

mean = tf.metrics.Mean()

for epoch in range(EPOCHS):
    start = time.time()

    mean.reset_states()
    for (batch_n, (inp, target)) in enumerate(dataset):
        logs = model.train_step([inp, target])
        mean.update_state(logs['loss'])

        if batch_n % 50 == 0:
            template = f"Epoch {epoch+1} Batch {batch_n} Loss {logs['loss']:.4f}"
            print(template)

    # saving (checkpoint) the model every 5 epochs
    if (epoch + 1) % 5 == 0:
        model.save_weights(checkpoint_prefix.format(epoch=epoch))

    print()
    print(f'Epoch {epoch+1} Loss: {mean.result().numpy():.4f}')
    print(f'Time taken for 1 epoch {time.time() - start:.2f} sec')
    print("_"*80)

model.save_weights(checkpoint_prefix.format(epoch=epoch))

Epoch 1 Batch 0 Loss 2.1913


Epoch 1 Batch 50 Loss 2.0591


Epoch 1 Batch 100 Loss 1.9363


Epoch 1 Batch 150 Loss 1.8937



Epoch 1 Loss: 1.9814
Time taken for 1 epoch 12.44 sec
________________________________________________________________________________


Epoch 2 Batch 0 Loss 1.8354


Epoch 2 Batch 50 Loss 1.7515


Epoch 2 Batch 100 Loss 1.6990


Epoch 2 Batch 150 Loss 1.6749



Epoch 2 Loss: 1.7090
Time taken for 1 epoch 11.45 sec
________________________________________________________________________________


Epoch 3 Batch 0 Loss 1.5859


Epoch 3 Batch 50 Loss 1.5785


Epoch 3 Batch 100 Loss 1.5548


Epoch 3 Batch 150 Loss 1.5089



Epoch 3 Loss: 1.5524
Time taken for 1 epoch 11.49 sec
________________________________________________________________________________


Epoch 4 Batch 0 Loss 1.4963


Epoch 4 Batch 50 Loss 1.4674


Epoch 4 Batch 100 Loss 1.4629


Epoch 4 Batch 150 Loss 1.4254



Epoch 4 Loss: 1.4550
Time taken for 1 epoch 11.26 sec
________________________________________________________________________________


Epoch 5 Batch 0 Loss 1.3884


Epoch 5 Batch 50 Loss 1.4480


Epoch 5 Batch 100 Loss 1.3669


Epoch 5 Batch 150 Loss 1.3619



Epoch 5 Loss: 1.3870
Time taken for 1 epoch 11.19 sec
________________________________________________________________________________


Epoch 6 Batch 0 Loss 1.3157


Epoch 6 Batch 50 Loss 1.3346


Epoch 6 Batch 100 Loss 1.3065


Epoch 6 Batch 150 Loss 1.2660



Epoch 6 Loss: 1.3341
Time taken for 1 epoch 11.25 sec
________________________________________________________________________________


Epoch 7 Batch 0 Loss 1.3223


Epoch 7 Batch 50 Loss 1.2794


Epoch 7 Batch 100 Loss 1.2886


Epoch 7 Batch 150 Loss 1.3036



Epoch 7 Loss: 1.2888
Time taken for 1 epoch 11.10 sec
________________________________________________________________________________


Epoch 8 Batch 0 Loss 1.2318


Epoch 8 Batch 50 Loss 1.2245


Epoch 8 Batch 100 Loss 1.2677


Epoch 8 Batch 150 Loss 1.2397



Epoch 8 Loss: 1.2480
Time taken for 1 epoch 11.13 sec
________________________________________________________________________________


Epoch 9 Batch 0 Loss 1.2021


Epoch 9 Batch 50 Loss 1.2654


Epoch 9 Batch 100 Loss 1.2190


Epoch 9 Batch 150 Loss 1.1929



Epoch 9 Loss: 1.2083
Time taken for 1 epoch 11.31 sec
________________________________________________________________________________


Epoch 10 Batch 0 Loss 1.1429


Epoch 10 Batch 50 Loss 1.1642


Epoch 10 Batch 100 Loss 1.1455


Epoch 10 Batch 150 Loss 1.1687



Epoch 10 Loss: 1.1684
Time taken for 1 epoch 11.55 sec
________________________________________________________________________________
